In [19]:
import numpy as np

"""
算法步骤
输入:线性可分的数据集T,i=1,2,…,N;学习率n(0<n≤1); 输出: a,b
(1) a = 0,b = 0; 
(2)计算xi和xj的内积矩阵Gram_matrix(对偶形式节省时间的关键所在)
(3)在训练集中选取数据(xi,yi); 
(4)如果yi([∑j->N aj*yj*xj·xi] + b) <= 0 , ai += n(第i个实例点的迭代次数增加一个学习率)  b += n*yi
(5)转至(3)直到没有误分类数据。

"""


def update(item, i):    # 更新实例点
    global alpha, b
    alpha[i][0] += l    # 第i个实例点的迭代次数增加一个学习率
    b += l*item[-1]
    print(alpha, b)


def check(_GramMatrix):  # 对应算法第四步
    separated_flag = True  # 默认无错误分类点
    res = 0
    i = 0
    for train_item in train_set:
        yi = train_item[-1]
        for j in range(train_set.shape[0]):
            yj = train_set[j][-1]   # 第j个实例点
            aj = alpha[j][0]    # 第j个实例点的迭代次数
            # 计算∑（j->N） aj* yj * xj·xi
            res += aj * yj * _GramMatrix[i][j]
        # print(res)
        # 计算 (𝑦(𝑖)*∑alpha(j)*𝑦(𝑗)）*𝑥(𝑗)∙𝑥(𝑖)≤0
        if (res + b) * yi <= 0:
            separated_flag = False
            update(train_item, i)
        res = 0
        i += 1
    return separated_flag


def get_GramMatrix(_train_set):  # 计算内积矩阵
    shape = _train_set.shape
    matrix = np.zeros((shape[0] ,shape[0]))

    item_list = []
    for train_item in _train_set:
        item_list.append(train_item[:-1])

    for i in range(shape[0]):
        for j in range(shape[0]):
            matrix[i][j] = np.vdot(item_list[i], item_list[j])

    print(matrix)
    return matrix


if __name__ == '__main__':
    train_set = np.array([[3, 3, 1],  # 设置训练集
                          [4, 3, 1],
                          [1, 1, -1]])
    # train_set1 = np.random.normal(3, size=(10, 3))
    # train_set2 = np.random.normal(7, size=(10, 3))
    # train_set = np.concatenate((train_set1, train_set2), axis=0)
    # 设置初值
    l = 1  # 学习率
    alpha = np.zeros((train_set.shape[0], 1), int) * l  # 当学习率（步长）为1时，alpha就是歌实例点更新的次数
    b = 0  # 偏置
    w = 0  # 权值

    GramMatrix = get_GramMatrix(train_set)
    for i in range(50):  # 迭代50次
        if check(GramMatrix):
            print("第{}次完成全部分离".format(i))
            break

    for i, item in enumerate(train_set):
        w += alpha[i][0] * item[-1] * item[:-1]

    print("参数为：w = {}, b = {}".format(w, b))




[[18. 21.  6.]
 [21. 25.  7.]
 [ 6.  7.  2.]]
[[1]
 [0]
 [0]] 1
[[1]
 [0]
 [1]] 0
[[1]
 [0]
 [2]] -1
[[1]
 [0]
 [3]] -2
[[2]
 [0]
 [3]] -1
[[2]
 [0]
 [4]] -2
[[2]
 [0]
 [5]] -3
第5次完成全部分离
参数为：w = [1 1], b = -3


In [18]:
beta = np.zeros((train_set.shape[0], 1))
beta[1][0] += 1
for j in beta:
    print(j)

[0.]
[1.]
[0.]
